### ISSUE TITLE
[ENH] Margins of sidebar need prettification

### ISSUE THREAD

**Issue by TimVanMourik** [TimVanMourik/Armadillo#5]
The sidebar should stretch the entire height of the window, but it doesn't. This needs to be fixed, and/or the design of the page should be fixed in general.

**Comment by dokato** [comment]
@TimVanMourik I checked your recent changes and the camera page doesn't look well for me (mac, chrome 67). Sidebar hides as only camera starts running and the resolution is too big - I need to scroll down to see the bottom part of the video. Actually, I liked the design where the QR code was still visible on the side.

I think that maybe some sketch design would be handy to have first, before introducing any amendments, that we know where to go.

**Comment by TimVanMourik** [comment]
Ooh, really, sorry, this is what it lloks like for me. The sidebar is now toglleable with the orange plus sign. I intended the layout to be the same as the original. I’m happy to have it toggled on by default instead.

And yes, I suppose first making a sketch-up of the layout is a good idea :)

<img width="1024" alt="png image" src="https://user-images.githubusercontent.com/6152205/41964404-2419ad5c-79fa-11e8-98ea-8127a90dcd0d.png">

**Comment by dokato** [comment]
In my browser it looks like this.
![screen shot 2018-06-27 at 10 53 32](https://user-images.githubusercontent.com/4547289/41966967-6a800f90-79f8-11e8-84b0-f7b0fa701f3f.png)
Image from camera is full-screen and sidebar is floating on top of it and gets cutted on the top.

Plus, when I don't press toggle the sidebar before the camera starts running, the "+" button escapes from my screen.

**Comment by dokato** [comment]
And @TimVanMourik WDYT about creating another "devarmadillo" heroku app for development and leave the current one to serve as "production" server to which we merge only content we're happy with and sure of?

**Comment by TimVanMourik** [comment]
Yes, that's definitely the more professional way! I made a 'dev' branch.

**Comment by dokato** [comment]
I checked other browsers and the problem with sidebar still occurs. Moreover, when camera gets ready I cannot see toggle button anymore.

**Comment by TimVanMourik** [comment]
Bug's been fixed. From here on, it's more of an enhancement.

**Comment by TimVanMourik** [comment]
Closing issue because new sidebar
